config/routes.rb
class ActionDispatch::Routing::Mapper

  def draw(routes_name)
    instance_eval(
      File.read(
        Rails.root.join("config/routes/#{routes_name}.rb")
      )
    )
  end

end

Rails.application.routes.draw do
  resources :products
  mount Payola::Engine => "/payola", as: :payola
  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    get "/logout" => "sessions#destroy", :as => :logout
    get "/signup" => "registrations#new", :as => :signup
    scope "my" do
      get "profile", to: "registrations#edit"
      put "profile/update", to: "registrations#update"
      get "password/edit", to: "registrations#edit_password"
      put "password/update", to: "registrations#update_password"
    end
  end

  unauthenticated do
    get "/logout" => redirect("/")
  end

  authenticate :user, ->(u) { u.super_admin? } do
    draw :administrate
    namespace :superadmin do
      root to: "users#index"
      draw :designs
      resources :users
    end
  end

  get "pages/about"
  get "pages/contact_us"
  resources :contacts, only: [:create]

  authenticated :user do
    get "/pages" => "pages#index", as: :pages
  end

  unauthenticated do
    as :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post "login" => "sessions#create", as: "login"
      end

      resources :users, only: %i[show create update destroy], constraints: { id: /.*/ }
    end
  end

  root "home#index"

end

app/views/shared/_bootstrap_flash.html.erb
<% flash.each do |name, message| %>
  <% if message.present? %>
    <div class="alert alert-<%= name.to_s == "alert" ? "danger" : "success" %>">
      <a class="close" data-dismiss="alert">×</a>
      <%= content_tag(:div, message, id: "flash_#{name}" if message.is_a?(String)) %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="ui vertical footer segment">
  <div class="ui center aligned container">
    <%= image_tag("logo.png", class: "ui centered mini image") %>
    <div class="ui horizontal inverted small divided link list">
      <p>©2011–<%= Time.zone.now.strftime("%Y") %> Shadowfax Demo. All rights reserved. <a>Privacy</a> and <a>Terms</a></p>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="ui modal" data-ui-behavior="modal">
  <i class="close icon"></i>
  <div class="header">
    <%= yield(:modal_title) %>
  </div>
  <div class="content">
    <%= yield(:modal_body) %>
  </div>
</div>

app/views/shared/_page_header.erb
<div class="page-header">
  <% if content_for?(:title) %>
    <h1><%= content_for(:title) %></h1>
    <%= content_for(:page_subhead) %>
  <% else %>
    <h1>Untitled</h1>
    <p>Don’t forget to set <code>provide(:title)</code> for this view!</p>
  <% end %>
</div>

app/views/shared/_sidebar_items.html.erb
<div class="item toc-only">
  <div class="ui input"><input type="text" placeholder="Search..."></div>
</div>
<div class="item side-menu-only">
  <%= image_tag("logo.png", class: "ui mini image middle aligned right spaced") %>
  <span>Shadowfax Demo</span>
</div>
<%= nav_link("Dashboard", root_path) %>
<%= nav_link("Contact us", pages_contact_us_path) %>
<%= nav_link("About", pages_about_path) %>
<div class="item">
  <div class="header">Templates</div><!-- /.header -->
  <div class="menu">
    <%= nav_link("Index", superadmin_designs_templates_index_path) %>
    <%= nav_link("Show", superadmin_designs_templates_show_path) %>
    <%= nav_link("New", superadmin_designs_templates_new_path) %>
    <%= nav_link("Dashboard", superadmin_designs_templates_dashboard_path) %>
    <%= nav_link("Settings", superadmin_designs_templates_settings_path) %>
  </div><!-- /.menu -->
</div><!-- /.item -->

app/views/shared/_superadmin_nav.html.erb
<%= link_to("Users", superadmin_users_path, class: "item") %>

app/views/shared/_top_menu.html.erb
<div class="ui top fixed borderless inverted main menu">
  <div class="ui container">
    <a class="item js-open-sidebar" id="menu-button">
      Menu
    </a>

    <div class="right menu">
      <div class="ui category search item">
        <div class="ui inverted transparent icon input">
          <input class="prompt" type="text" placeholder="Search...">
          <i class="search link icon"></i>
        </div>
        <div class="results"></div>
      </div>
      <div class="ui floating pointing dropdown top right icon item" data-ui-behavior="dropdown">
        <i class="wrench icon"></i>
        <div class="menu">
          <%= link_to("Change Password", password_edit_path, class: "item") %>
          <% if super_admin_signed_in? %>
            <div class="divider"> </div>
            <div class="header">Superadmin</div>
            <%= link_to("Superadmin Dashboard", superadmin_root_path, class: "item") %>
            <%= link_to(
              "Routes",
              "/rails/info/routes",
              target: "_blank",
              rel: "noopener noreferrer",
              class: "item"
            ) %>
            <%= link_to(
              "Mailers",
              "/rails/mailers",
              target: "_blank",
              rel: "noopener noreferrer",
              class: "item"
            ) %>
            <%= link_to(
              "Admin Dashboard",
              admin_root_path,
              target: "_blank",
              rel: "noopener noreferrer",
              class: "item"
            ) %>
          <% end %>
        </div>
      </div>
      <div class="item">
        <div>
          <a class="ui red circular label">2</a>
        </div>
      </div><!-- /.item -->
      <div class="ui floating pointing dropdown top right item" data-ui-behavior="dropdown">
        <img class="ui avatar image" src="http://placehold.it/250">
        <div class="menu">
          <%= link_to("My Account", profile_path, class: "item") %>
          <%= link_to("Sign Out", destroy_user_session_path, method: :delete, class: "item") %>
        </div>
      </div>
    </div>
  </div>
</div>